GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
GCS_BUCKET_NAME = "GCS_BUCKET_NAME"
PROJECT_ID = "PROJECT_ID"
DOCKER_ENV_VARS_PLACEMENT = "#*COPY_ENV_VARS_HERE*\n"
DOCKERFILE = "Dockerfile"
DOCKERIGNORE = ".dockerignore"
GCP_EMAIL = "GCP_EMAIL"
MODEL_ROUTE = "MODEL_ROUTE"
SKLEARN = "sklearn"
TF = "tf"
TF_SERVING_FOLDER = "tf_model"
CONTAINER_ERROR = "Something went wrong in building the container."
CLOUDBUILD = "cloudbuild.yaml"
DATA_FILE_EXTS = [".csv", ".txt"]
MODEL_FILE_EXTS = ["tf", ".pb", ".h5", ".joblib", ".pkl"]
INFRA_FILE_EXTS = [".dockerignore", "Dockerfile"]
